### ISSUE TITLE
SF Scalabridge workshop at Domino Data Lab April 2017

### ISSUE THREAD

**Issue by akanshmurthy** [scalabridge/organization#7]
I'm interested in helping organize a Scala workshop in April at Domino Data Lab and I'd like to get the conversation started :)

**Comment by robinske** [comment]
Awesome! Let me know if I can help!

**Comment by akanshmurthy** [comment]
Awesome! I know there are organizing docs/guidelines for RailsBridge. Is there something similar for ScalaBridge (i.e. what steps are necessary for me to start executing?)?

**Comment by robinske** [comment]
Start here: https://github.com/scalabridge/organization/blob/master/plan-a-workshop.md and let me know if/when you run into any specific issues or have questions!

**Comment by akanshmurthy** [comment]
Ok, thanks. What's a good date in your mind? April? When can I officially create the event on Bridge Troll)? Once I have confirmed a sponsor/venue?

**Comment by robinske** [comment]
Yeah once the date & location is confirmed you can create the event. Twilio (my company) can sponsor! See a past event for reference: https://www.bridgetroll.org/events/333

**Comment by akanshmurthy** [comment]
Cool, my company would be happy to host/provide the venue. What date works best for you? I checked with our team and any of the first 3 weekends in April would be fine.  

Awesome! Would Twilio be sponsoring the food/snacks?

**Comment by robinske** [comment]
Yeah those dates work for me. And yes we could cover
food/snacks/incidentals

**Comment by akanshmurthy** [comment]
Ok, great! Shall we set it then for April 6th/7th? I can create an event now (or wait if you think it's too soon).

**Comment by robinske** [comment]
No, let’s do April 20-21. I can’t do 6-7

**Comment by akanshmurthy** [comment]
Cool, done! I've created a draft here: https://www.bridgetroll.org/events/388

Let me know what you would like to include for Twilio and any logos. Thanks!

**Comment by robinske** [comment]
Awesome, I updated the event with our logo - I also emailed the Bridge Foundry folks
about donating. Let's wait to publish until
they get back to us, we have a bunch of time to put it live. I'm excited!
Thanks for spearheading this one, Akansh!

**Comment by akanshmurthy** [comment]
Cool! Thanks!

Yes, excited! My pleasure.

**Comment by akanshmurthy** [comment]
The event has been approved! Let me know when you think would be a good date to make it public.

Also, let me know how you want to tackle ordering food and if I need to know anything to facilitate food delivery (elevator access, etc.).

**Comment by robinske** [comment]
Hi @akanshmurthy - you should plan the logistics of the event including food. Other SF workshops have spent <$1800 per event, so that's a good budget to stay within. Per Diana's email, I'll get Twilio set up as a sponsor for the event, then you can do steps 3 and 4:

3. Submit a [grant application](https://operations.bridgefoundry.org/grants/funded-grants/) for the approximate amount you expect to need total for the workshop

4. Keep all receipts for workshop expenses following our [guidelines](https://operations.bridgefoundry.org/using-funds/README/) and then submit a [reimbursement request](https://operations.bridgefoundry.org/using-funds/expense-reports/) after the workshop (if you can't afford to get reimbursed after the fact, let us know and we can coordinate with you to pay for expenses directly.)

**Comment by robinske** [comment]
One more thing to confirm about our sponsorship - we would like 5 minutes during the opening ceremony to show how Twilio works w/ Scala, I'll be doing that demo!

**Comment by robinske** [comment]
Oh, and let's still wait to make the event public until I can confirm Twilio's sponsorship!

**Comment by akanshmurthy** [comment]
Ok, sounds good. 

Sounds good on the 5 minutes.

Ok, sounds good. Sorry for the rush; I thought Twilio was already confirmed according to your earlier messages above but I now understand that it's a process :)

**Comment by robinske** [comment]
Yep that’s my bad, should have something for you by the end of the week

**Comment by akanshmurthy** [comment]
No worries! And, no rush. We have plenty of time :)

**Comment by akanshmurthy** [comment]
Hey, @robinske ! I was out of town last week but am back now and was wondering if you heard anything on your end yet.

**Comment by robinske** [comment]
Should be ok to go ahead and publish! FYI total budget is $1800 for the
event, that should be more than enough based on previous events!

**Comment by akanshmurthy** [comment]
Cool, I'll do that now!
