### ISSUE TITLE
ScalaBridge workshop at the 47 Degrees office prior to Lambda World Seattle

### ISSUE THREAD

**Issue by MaureenElsberry** [scalabridge/organization#8]
Hi, Kelley and crew,

We'd love to host a ScalaBridge workshop on Sunday, September 16th at the 47 Degrees office in Seattle.

[Lambda World Seattle](http://seattle.lambda.world/) will be Monday/Tuesday September 17th-18th so we thought it would be great to kick things off with an SB event. I'm sure we'll want to do something similar for Cádiz, but cannot confirm that at this point.

Still in initial planning stages but wanted to get the conversation started for this! I'm sorry if I missed this in the documents, but is there a required or estimated time-frame for the workshop curriculum to be taught?

Thanks,

Maureen
maureen.elsberry@47deg.com

**Comment by robinske** [comment]
Whatever works for you! Here's an example schedule: https://scalabridge.gitbooks.io/curriculum/content/

The curriculum pacing varies by student, but most people don't finish during the day. It is open source so we encourage folks to continue after the workshop. I would allot whatever amount of time makes sense for your team!

**Comment by MaureenElsberry** [comment]
Just as an update to this, here is the BridgeTroll listing: https://www.bridgetroll.org/events/440
